"""followers

Revision ID: 0b012d6a48d7
Revises: 811979b76ece
Create Date: 2022-07-06 15:10:01.771705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b012d6a48d7'
down_revision = '811979b76ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('Followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
