"""new fields in user model

Revision ID: 811979b76ece
Revises: 98c8f7425d2e
Create Date: 2022-07-05 14:53:36.579648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811979b76ece'
down_revision = '98c8f7425d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
