"""followers

Revision ID: e63fdc9b3668
Revises: 0b012d6a48d7
Create Date: 2022-07-06 15:16:20.425585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63fdc9b3668'
down_revision = '0b012d6a48d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'Followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('Followed_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['Followed_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
